### ISSUE TITLE
[Reference] Motion UI

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#10]
* [Cards](http://tympanus.net/Development/GridLoadingEffects/index2.html)
* [Buttons (Nina)](http://tympanus.net/Development/ButtonStylesInspiration)
* [Icon Buttons (Boris)](http://tympanus.net/Development/ClickEffects)
* [Fields (Minoru)](http://tympanus.net/Development/TextInputEffects)
* [Dialog](http://tympanus.net/Development/DialogEffects/annie.html)
* [Side Menu](http://codyhouse.co/demo/faq-template/index.html#0)
* [Top Menu](http://codyhouse.co/demo/secondary-sliding-navigation/index.html#0)
* [Top Menu (Hover)]( http://codyhouse.co/demo/style-guide-template/index.html#0)
* [Notifications] (http://tympanus.net/Development/NotificationStyles/bar-slidetop.html)
* [Text Input Fields] (http://tympanus.net/Development/TextInputEffects/index2.html)
* [Loaders] (http://connoratherton.com/loaders)

**Comment by zenorocha** [comment]
Moving to [a wiki](https://github.com/liferay-apps/ui-kit/wiki/Motion).
