### ISSUE TITLE
Changes on Docs Cell and List

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#22]
- [ ] the components' cells should have width of 688, instead of 710;
- [ ] the components' title goes up 4px;
- [ ] the components' description goes up 10px. And, it should have an alpha of 0.40;
- [ ] the box for the code goes up 2px;
- [ ] the box for the code has 528px and margins of 14px;
- [ ] the box for the code should display the (code's) line counter;
- [ ] the box for the code should not display any scrollbar;
- [x] the box for the code should has the font as [Fira Mono Normal - 400] (https://www.google.com/fonts/specimen/Fira+Mono);
- [ ] the box for the code should has those colors for the font: #1f7aff (blue), #ff5653 (red), #71c358 (green), #233240 (dark blue);
- [ ] the distance between the sidebar and the cells' column should be 32px;
- [ ] the distance between the cells (height) should be 24px;

**Comment by zenorocha** [comment]
This issue affects pretty much the site UI. Closing it for now...
