### ISSUE TITLE
[Review] Modal

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#26]
- [x] the header divisor (line) should has the same color of the texts (#233240), but with alpha of 0.08;
- [x] the header height should be composed of padding top/bottom of 21px;
- [x] the close button is being crushed by the issue we have with icons (see icons' issue), it should has 1.2rem and it should be bottom align with the header's title font;
- [x] the modal body should has these values:   padding-bottom: 60px; padding-left: 22px; padding-right: 44px; padding-top: 21px; width: 398px;
- [ ] the modal body should has height of 188px;

**Comment by zenorocha** [comment]
Modal's body height is flexible depending on the content.
