### ISSUE TITLE
[Review] Modal: Dialog

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#27]
- [ ] there's a little glitch when the buttons are hovered;
- [x] the dialog font-size should be 1.3rem (without affect the regular dialog description font-size);
- [x] the dialog's body should has these values: padding-bottom: 60px; padding-left: 22px; padding-right: 44px; padding-top: 21px; width: 398px;
- [x] the dialog's bottom should has these values: padding-bottom: 12px; padding-left: 12px; padding-right: 12px; padding-top: 12px; text-align: right; width: 440px;

**Comment by zenorocha** [comment]
@eduardolundgren also mentioned this glitch but I can't see it.

**Comment by eduardolundgren** [comment]
I could replicate the glitch issue. It's an issue caused by setting the button opacity on hover and the "centered" modal that uses translationX/Y.

I am going to separate that to a different issue.

**Comment by eduardolundgren** [comment]
Continues on https://github.com/liferay-apps/ui-kit/issues/46
