### ISSUE TITLE
Improve Form: Input

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#32]
- [ ] when the text is in focus, instead of change the stroke color according the main color, it'll be better just change its alpha to 1.0 (it's 0.2, on regular state). The reason of this resides in if the user select a color for the main color that is similar to red, then the box looks like as an error state;

**Comment by vitorfernandes** [comment]
- [ ] On the cell, their top and bottom lines is appearing blurred.

obs: let's avoid all blurred shapes that we will see on the whole UI, if you find one, kill it.

**Comment by zenorocha** [comment]
First one is done.

Second one couldn't be reproduced even in a Dell monitor.
