### ISSUE TITLE
Review shortlist of components

### ISSUE THREAD

**Issue by zenorocha** [liferay-apps/ui-kit#5]

**Comment by vitorfernandes** [comment]
- [ ] Space between the buttons, at least 12px;

**Comment by vitorfernandes** [comment]
- [ ] Let's use these pics on the avatar: photos (in this ordering).

![photo-1](https://cloud.githubusercontent.com/assets/11338156/6708570/4d6bb696-cd50-11e4-97f1-8e11067d0cb9.png)
![photo-2](https://cloud.githubusercontent.com/assets/11338156/6708571/4d6cce6e-cd50-11e4-862f-93145a92db3f.png)
![photo-3](https://cloud.githubusercontent.com/assets/11338156/6708572/4d713300-cd50-11e4-8be8-e9ca01153311.png)

**Comment by vitorfernandes** [comment]
- [ ] All buttons' labels should have font weight semi-bold;

**Comment by zenorocha** [comment]
What are the names for those avatars?
