### ISSUE TITLE
Spaces between Cells 

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#51]
- [ ] all spaces between each cell should be, exactly, 24px always. Ex: top bar until the first cell and the sidebar, the sidebar and the cells list, the cells on the list, etc. This space can be applied, also, to the distance between the last cell and the bottom of the page;

**Comment by zenorocha** [comment]
- [x] Space between topbar until sidebar and first cell
- [x] Space between cells on the list
- [x] Space between last cell and the bottom of the page

**Comment by zenorocha** [comment]
The only one that wasn't applied was the space between sidebar and the cells list since that is applied by the fluid grid.
