### ISSUE TITLE
Cells

### ISSUE THREAD

**Issue by vitorfernandes** [liferay-apps/ui-kit#54]
- [ ] In this comp, their borders are appearing blurred. Let's make it looks sharp and clean.

**Comment by zenorocha** [comment]
There's no way for a border to be set as blurred.

![screen shot 2015-04-24 at 9 32 24 am](https://cloud.githubusercontent.com/assets/398893/7323651/1b4d38ce-ea65-11e4-99d2-9df119320dca.png)

**Comment by zenorocha** [comment]
Not reproducible.
