### ISSUE TITLE
Make List component more generic

### ISSUE THREAD

**Issue by zenorocha** [liferay-apps/ui-kit#62]
My proposal is to:

1. Rename `img` attribute to `avatar`
2. Rename `img.src` attribute to `avatar.content` which should be able to receive a HTML content
3. Rename `content` attribute to `textPrimary` which should be able to receive a HTML content
4. Rename `help` attribute to `textSecondary` which should be able to receive a HTML content

**Comment by eduardolundgren** [comment]
:+1: I can change that.
